services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www
      - .docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - php

  php:
    build: .docker/php
    volumes:
      - .:/var/www
